---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopixiu-event
  labels:
    apps: gopixiu-event
spec:
  selector:
    matchLabels:
      apps: gopixiu-event
  template:
    metadata:
      name: gopixiu-event
      labels:
        apps: gopixiu-event
    spec:
      serviceAccountName: events
      containers:
        - name: gopixiu-event
          image: jacky06/gopixiu-event:v0.0.1
          imagePullPolicy: IfNotPresent
          command: ["gopixiu-event","--elasticsearch.address=http://10.249.4.147:9200","--elasticsearch.password=elastic","--elasticsearch.username=elasticsearch"]