apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopixiu-event
  labels:
    apps: gopixiu-event
spec:
  selector:
    matchLabels:
      apps: gopixiu-event
  template:
    metadata:
      name: gopixiu-event
      labels:
        apps: gopixiu-event
    spec:
      containers:
      - name: gopixiu-event
        image: gopixiu-event:v0.0.1
        imagePullPolicy: IfNotPresent